version: '3.8'

services:
  web_image_api:
    restart: on-failure
    build: .
    command:
       sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: web_image_api
    volumes:
      - .:/usr/src/web_image_api
    ports:
      - "8000:8000"
    networks:
      - app_network

  db:
    image: postgres:14-alpine
    container_name: postgres_db_image_api
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app_network
networks:
  app_network:
    driver: bridge